from __future__ import annotations

from typing import Any

class Session:
    def query(self, *args: Any, **kwargs: Any) -> Any: ...
    def add(self, *args: Any, **kwargs: Any) -> Any: ...
    def commit(self) -> None: ...
    def refresh(self, *args: Any, **kwargs: Any) -> None: ...
    def close(self) -> None: ...

def sessionmaker(*args: Any, **kwargs: Any) -> Any: ...
def declarative_base(*args: Any, **kwargs: Any) -> Any: ...
def relationship(*args: Any, **kwargs: Any) -> Any: ...
